//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileServer.Utils.LogHelper {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileServer.Utils.LogHelper.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clicked add button.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added new alumno to the alumnos list.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to deserialize object.
        /// </summary>
        internal static string deserialize {
            get {
                return ResourceManager.GetString("deserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cannot write line.
        /// </summary>
        internal static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created a new guid.
        /// </summary>
        internal static string guid {
            get {
                return ResourceManager.GetString("guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded alumnos list.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App.Config path chosen.
        /// </summary>
        internal static string path1 {
            get {
                return ResourceManager.GetString("path1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Environment path chosen.
        /// </summary>
        internal static string path2 {
            get {
                return ResourceManager.GetString("path2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Started app.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded alumnos list.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Returned alumno.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to write json.
        /// </summary>
        internal static string writingJson {
            get {
                return ResourceManager.GetString("writingJson", resourceCulture);
            }
        }
    }
}
