//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileServer.Infrastructure.Repository {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileServer.Infrastructure.Repository.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App.config.
        /// </summary>
        internal static string AppConf {
            get {
                return ResourceManager.GetString("AppConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trying to deserialize object.
        /// </summary>
        internal static string DesObj {
            get {
                return ResourceManager.GetString("DesObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a error.
        /// </summary>
        internal static string err {
            get {
                return ResourceManager.GetString("err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, cannot write line.
        /// </summary>
        internal static string erWrite {
            get {
                return ResourceManager.GetString("erWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fileName.
        /// </summary>
        internal static string fileN {
            get {
                return ResourceManager.GetString("fileN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FileServer.Presentation.WinSite.Resource.
        /// </summary>
        internal static string FilePresentWinReso {
            get {
                return ResourceManager.GetString("FilePresentWinReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a load error: .
        /// </summary>
        internal static string loadEr {
            get {
                return ResourceManager.GetString("loadEr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added new alumno to the alumnos list.
        /// </summary>
        internal static string newAlum {
            get {
                return ResourceManager.GetString("newAlum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created a new guid.
        /// </summary>
        internal static string newGui {
            get {
                return ResourceManager.GetString("newGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App.Config path chosen.
        /// </summary>
        internal static string path1 {
            get {
                return ResourceManager.GetString("path1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Environment path chosen.
        /// </summary>
        internal static string path2 {
            get {
                return ResourceManager.GetString("path2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Returned alumno.
        /// </summary>
        internal static string reAlum {
            get {
                return ResourceManager.GetString("reAlum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable de entorno.
        /// </summary>
        internal static string varEnt {
            get {
                return ResourceManager.GetString("varEnt", resourceCulture);
            }
        }
    }
}
